### ISSUE TITLE
Center of Group

### ISSUE THREAD

**Issue by zhuny** [zhuny/algebra#25]
## 참고
* https://en.wikipedia.org/wiki/Center_(group_theory)

## Todo
* [x] Center 구현하기
* [ ] Center가 맞는지 확인하기 위한 기타 기능들
    * [x] Normal Subgroup인지 확인하기
    * [ ] 다음 class들 구현하기
        * [ ] Quaternion Group
        * [x] Symmetric Group
        * [x] Alternating Group
        * [ ] Dihedral Group
